spring:
  application:
    name: spring-batch

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  batch:
    jdbc:
      initialize-schema: always

property:
  exchange:
    authKey: U1iyu5OrdUAeWhU9i5OqCC6eJBrJ5Mof
    data: AP01